### ISSUE TITLE
onUpdateCb operates already on copy of state, so unchecking parents not possible from within

### ISSUE THREAD

**Issue by mastef** [azizali/react-super-treeview#10]
onUpdateCb operates already on the copy of this.state.data, so unchecking parents not possible from within callback, as changing this.state.data will be overwritten by the internal - cloned - variable.

Possible fix : supply the whole data tree as 2nd parameter to `onUpdateCb`

**Comment by azizali** [comment]
The whole data is added as a callback to onUpdateCb already, hence if some properties need to be modified, it can be done on the `onUpdateCb` function
