### ISSUE TITLE
Add possibility to style list items that don't have a dropdown arrow

### ISSUE THREAD

**Issue by mastef** [azizali/react-super-treeview#11]
Currently list items without a dropdown are moved further to the left. 

In : https://github.com/azizali/react-super-treeview/blob/master/src/index.js#L138-L147 could change  : 

```diff
        if (isExpandable(node, depth)) {
            return (
                <div
                    className={`super-treeview-triangle-btn ${className}`}
                    onClick={() => {
                        this.handleExpandToggle(node);
                    }}
                />
            );
+        } else {
+           return (
+               <div
+                   className={`super-treeview-triangle-btn super-treeview-triangle-no-btn`}
+               />
+           );
         }
```
Then the app dev can style this element by adjusting `.super-treeview-triangle-no-btn { width: 10px; height: 10px; }` etc. so we get : 

![image](https://user-images.githubusercontent.com/762297/41033490-fd7d6002-69b0-11e8-96a1-673c6a26d293.png)
 
instead of : 

![image](https://user-images.githubusercontent.com/762297/41033526-1cdcbec0-69b1-11e8-9040-2890d7eae750.png)

**Comment by azizali** [comment]
This is a great idea, I have implemented this. Thanks
