### ISSUE TITLE
No way to make local edits

### ISSUE THREAD

**Issue by eulertour** [azizali/react-super-treeview#20]
I'm trying to make some local edits to the library, but I don't see a way to get it running other than installing from npm, which prevents editing.

I've tried forking and installing directly from github, but the resulting directory in `node_modules` doesn't have a `src/` or `dist/` directory. I've also tried cloning the repo into my project, running `npm install` and `npm build`, and trying to import it from the repo, but it causes some errors in lodash:
```
./src/components/react-super-treeview/node_modules/lodash/lodash.js
  Line 419:    Unexpected use of 'self'  no-restricted-globals
  Line 419:    Unexpected use of 'self'  no-restricted-globals
  Line 419:    Unexpected use of 'self'  no-restricted-globals
  Line 419:    Unexpected use of 'self'  no-restricted-globals
  Line 17083:  'define' is not defined   no-undef
  Line 17083:  'define' is not defined   no-undef
  Line 17092:   'define' is not defined   no-undef
```
Any help on this would be appreciated.

**Comment by azizali** [comment]
yes `node_modules` will not have those folders.

- `src` folder will be there when you clone the repo
