### ISSUE TITLE
Select parent when child selected

### ISSUE THREAD

**Issue by renant** [azizali/react-super-treeview#21]
I'm trying to select a parent when one of your children is selected, can I do that?

**Comment by azizali** [comment]
Great question.

The `onCheckToggleCb` callback function will only get the list of nodes that got toggled.
The `onUpdateCb`callback will get the full data.

You can determine the parent of checked/unchecked node by finding it in the full tree.

**Comment by renant** [comment]
So the correct one would implement on the `onUpdateCb` callback, I was trying on the` onCheckToggleCb` callback ...

I'll try later with `onUpdateCb` and report here

Thank you

**Comment by azizali** [comment]
Perfect thanks.

**Comment by renant** [comment]
Hi @azizali , how's it going?

Sorry for the delay, I was able to do this through a combination of 'onCheckToggleCb' and 'onUpdateCb'

I got the last selected node in 'onCheckToggleCb' and found the parent  by reference in 'onUpdateCb' and checked this

Thanks for the help, and sorry my bad english

**Comment by azizali** [comment]
Great. Awesome.

**Comment by c623700** [comment]
> Hi @azizali , how's it going?
> 
> Sorry for the delay, I was able to do this through a combination of 'onCheckToggleCb' and 'onUpdateCb'
> 
> I got the last selected node in 'onCheckToggleCb' and found the parent by reference in 'onUpdateCb' and checked this
> 
> Thanks for the help, and sorry my bad english

I would interest in how you implement your solution, specially how to manage to pass the reference of the box that was checked, to the onUpdateCb. Thanks in advance

**Comment by ghost** [comment]
I strongly recommend using react-checkbox-tree if you need this functionality (which is a must for a tree-view component). I hardly managed to check the upper parents but even in that case component doesn't half-check the parent and couldn't make it do that since it's not created considering this functionality.
