### ISSUE TITLE
have a problem in styling

### ISSUE THREAD

**Issue by zahrahajilary** [azizali/react-super-treeview#22]
thanks you for sharing this component
i have a problem in styling , i did every thing step by step base on read me page but , actually it dosen't work you can see the picture here 
![Screenshot from 2019-04-17 17-33-27](https://user-images.githubusercontent.com/15054705/56289828-1b434600-6137-11e9-8ed0-bd67c7aeb28b.png)

and i got error :

> index.js:1446 Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

my code here : 
`
import React, { Component } from 'react'
import SuperTreeview` `from 'react-super-treeview'
import 'react-super-treeview/dist/style.css'
class ListTree extends Component {
    constructor(){
        super();
        // SET YOUR DATA
        this.state = {
            data: [
                {
                    id: 1,
                    name: 'Parent A'
                },
                {
                    id: 2,
                    name: 'Parent B',
                    isExpanded: true,
                    isChecked: true,
                    children: [
                        {
                            id: 1,
                            name: 'Child 1'
                        },
                        {
                            id: 2,
                            name: 'Child 2'
                        }
                    ]
                }
            ]
        };
    }
 
    render(){
        return (
            <SuperTreeview
                data={ this.state.data }
                onUpdateCb={(updatedData) => {
                    this.setState({data: updatedData})
                }}
            />
        );
    }
}
 export default ListTree`

**Comment by azizali** [comment]
There may be some other CSS in your project affecting it.

Can you show the live demo?

**Comment by zahrahajilary** [comment]
sure, actually i used material kit react dashboard pro, every thing are encapsulating , but may be related to this css

**Comment by zahrahajilary** [comment]
i cant send you my records because github didn't support mkv

**Comment by zahrahajilary** [comment]
thank you  so much  , I found my problem , you are right , I used CSS globally that affected on labels
