### ISSUE TITLE
Why is this not working when we put the data in a different file?

### ISSUE THREAD

**Issue by rohitmarneni** [azizali/react-super-treeview#24]
In my render method, I have this:
```jsx
<SuperTreeView data={myData}/>
```

The `myData` variable has sample information taken from the sample demo. It works now. 

However, if I were to take this myData json array and put it in a different js file and export it from there and then import it in my react component jsx file, it wont work. Only the top level is displayed. The checkboxes or arrows wont go further.

**Comment by azizali** [comment]
Please share your code, maybe with codepen and I can take a look. It should
work.

**Comment by rohitmarneni** [comment]
My bad, it was a simple issue with updateCb callback. Thanks for your reply. Closing the issue. Have a nice day.
