### ISSUE TITLE
Relies on bootstrap css

### ISSUE THREAD

**Issue by mastef** [azizali/react-super-treeview#7]
When react-super-treeview is rendered in a page without a bootstrap.css, the arrows are displayed incorrectly. Maybe remove reliance on bootstrap, or add a note to the readme.

Without bootstrap : 
![image](https://user-images.githubusercontent.com/762297/40955842-e0268a88-68b6-11e8-94d0-9ea7850f8be4.png)

With bootstrap : 
![image](https://user-images.githubusercontent.com/762297/40955849-ee8b46ae-68b6-11e8-9aca-d699e996e627.png)

**Comment by azizali** [comment]
Hey @mastef thanks for reporting all these bugs, I am gonna look into each of them

**Comment by azizali** [comment]
This is now fixed in version 0.3.0
