### ISSUE TITLE
isExpandable / isCheckable as data properties

### ISSUE THREAD

**Issue by mastef** [azizali/react-super-treeview#9]
When constructing the initial data, we most likely know if this node should be expandable or not. Having a callback that runs on every child node might not be as performant. Would be good if we could just add `isExpandable: false` to the data instead : 

```
        this.state.data = [
            {
                id: 1,
                name: 'Parent A',
                isExpandable: false
            }
```

**Comment by azizali** [comment]
If there are no children, the children array will not be iterated on, hence there is no performance downfall.
